apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-webapp
spec:
  selector:
    matchLabels:
      app: java-webapp
  template:
    metadata:
      labels:
        app: java-webapp
    spec:
      containers:
      - name: java-webapp
        image: ojpascale/ovia-java-web-app:v1
        resources:
          requests:
            cpu: "250m"
            memory: "250Mi"
          limits:
            memory: "300Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080