apiVersion: v1
kind: Namespace
metadata:
  name: devops-ns
  labels: 
    team: devops
    tools: cicd-tools
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deploy
  namespace: devops-ns
spec:
  selector:
    matchLabels:
      app: jenkins-app
  template:
    metadata:
      labels:
        app: jenkins-app
    spec:
      containers:
      - name: jenkins-container
        image: jenkins/jenkins:lts-jdk21
        resources:
          requests:
            memory: "200Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

        volumeMounts:
        - name: jenkins-vol
          mountPath: /var/jenkins_home

      volumes:
      - name: jenkins-vol
        persistentVolumeClaim:
          claimName: jenkins-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: devops-ns
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: devops-ns
spec:
  selector:
    app: jenkins-app
  ports:
  - port: 80
    targetPort: 8080

