apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: ovia
spec:
  limits:
  - max:
      cpu: "500m"
      memory: "512Mi"
    min:
      cpu: "200m"
      memory: "256Mi"
    type: Container