apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress
  namespace: ovia-ns
spec:
  podSelector:
    matchLabels:
      app: mongo
  policyTypes:
  - Ingress 
  ingress:
    - from:
      - podSelector:
          matchLabels:
            name: config-app
      ports:
        - protocol: TCP
          port: 27017