# --------------------------
# Headless Service for StatefulSet
# --------------------------
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: dev
spec:
  clusterIP: None  # Headless service
  selector:
    app: mongod
  ports:
    - port: 27017
      targetPort: 27017

---

# --------------------------
# StatefulSet for MongoDB Replica Set
# --------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongod
  namespace: dev
spec:
  serviceName: mongodb-service
  replicas: 3
  selector:
    matchLabels:
      app: mongod
  template:
    metadata:
      labels:
        app: mongod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb-container
          image: mongo:7.0   # includes mongosh
          command:
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "MainRepSet"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-pvc
              mountPath: /data/db
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
  volumeClaimTemplates:
    - metadata:
        name: mongo-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
