---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hpa-deploy
  namespace: ovia-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      name: hpa-pods
  template:
    metadata:
      namespace: ovia-ns
      labels: 
        name: hpa-pods
    spec:
      containers:
      - name: hpa-container
        image: ojpascale/ovia-maven-web:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
          limits:
            cpu: 500m
            memory: 500Mi

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler 
metadata:
  name: ovia-hpa
  namespace: ovia-ns
spec:
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment 
    name: hpa-deploy
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource: 
      name: memory
      target: 
        type: Utilization
        averageUtilization: 70
---
apiVersion: v1
kind: Service
metadata:
  name: ovia-svc
  namespace: ovia-ns
spec:
  selector:
    app: hpa-pods
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080




