apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-webapp
spec:
  selector:
    matchLabels:
      app: java-webapp
  template:
    metadata:
      labels:
        app: java-webapp
    spec:
      containers:
      - name: java-webapp
        image: ojpascale/ovia-java-web-app:v1
        resources:
          requests:
            cpu: "250m"
            memory: "250Mi"
          limits:
            memory: "300Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: configmap-vol
          mountPath: "/usr/local/tomcat/conf/tomcat-users.xml"
          subPath: "tomcat-users.xml"
      volumes:
      - name: configmap-vol
        configMap:
          name: java-webapp-config
          items:
          - key: "tomcat-users.xml"
            path: "tomcat-users.xml"

---
apiVersion: v1
kind: Service
metadata:
  name: javaweb-svc
spec:
  type: NodePort
  selector:
    app: java-webapp
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: java-webapp-config
data:
  tomcat-users.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <tomcat-users xmlns="http://tomcat.apache.org/xml"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
              version="1.0">

  
    <user username="lsf" password="ovia" roles="admin-gui,manager-gui,manager-script"/>

    </tomcat-users>

