apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    app: java-webapp
spec:
  containers:
  - name: java-webapp-container
    image: ojpascale/ovia-shopping-cart:1.0
    ports:
    - containerPort: 8070
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: multi-svc
spec:
  type: NodePort
  selector:
    app: java-webapp
  ports:
  - port: 8070
    targetPort: 8070
    name: alpine
  - port: 80
    targetPort: 80
    name: nginx


