apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovia-deployment
  namespace: ovia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ovia-app
  template:
    metadata:
      labels:
        app: ovia-app
    spec:
      tolerations:
      - key: env
        operator: Equal
        value: dev
        effect: NoSchedule
      containers:
      - name: ovia-container
        image: ojpascale/ovia-maven-web:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
          limits:
            cpu: 1
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ovia-svc
  namespace: ovia
spec:
  selector:
    app: ovia-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
