apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: ovia
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
    count/pods: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovia-deployment
  namespace: ovia
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    minReadySeconds: 30
  selector:
    matchLabels:
      app: ovia-app
  template:
    metadata:
      labels:
        app: ovia-app
    spec:
      containers:
      - name: ovia-container
        image: ojpascale/ovia-maven-web:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
          limits:
            cpu: "1"
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ovia-svc
  namespace: ovia
spec:
  selector:
    app: ovia-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
